import type { Metadata } from "next";
import localfont from "next/font/local";
import "~/styles/globals.css";

interface RootLayoutProps {
  children: React.ReactNode;
}

const geist = localfont({
  src: [
    {
      path: "../assets/fonts/Geist-Regular.woff2",
      style: "normal",
      weight: "400",
    },
    {
      path: "../assets/fonts/Geist-Medium.woff2",
      style: "normal",
      weight: "500",
    },
    {
      path: "../assets/fonts/Geist-Bold.woff2",
      style: "normal",
      weight: "700",
    },
  ],
  variable: "--font-geist",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={geist.variable}>{children}</body>
    </html>
  );
}
